import type { Metadata } from "next";
import Direction from "@/components/Direction";

export const metadata: Metadata = {
  title: "minhtrifit | Project",
  description: "Generated by minhtrifit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-auto max-w-screen-lg px-3 py-6">
      <Direction />
      {children}
    </div>
  );
}
