import type { Metadata } from "next";
import Direction from "@/components/Direction";
import RoleProvider from "@/components/providers/RoleProvider";

export const metadata: Metadata = {
  title: "minhtrifit | Create",
  description: "Generated by minhtrifit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RoleProvider>
      <div className="mx-auto max-w-screen-lg px-3 py-6">
        <Direction />
        {children}
      </div>
    </RoleProvider>
  );
}
